
version: '3.8'
services:
  code-eva-db:
    image: postgres:15.2-alpine
    restart: no
    environment:
      - POSTGRES_USER=code-eva
      - POSTGRES_PASSWORD=code-eva
      - POSTGRES_DB=code-eva
    ports:
      - '5432:5432'
