
server:
  port: 8080
  servlet:
    context-path: "/api/"
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: false

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
            format_sql: true
            use_sql_comments: true
  datasource:
    url: jdbc:postgresql://localhost:5432/code-eva
    username: root
    password: root